from .node_inference_size_bucket import (
    NODE_CLASS_MAPPINGS as BUCKET_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BUCKET_DISPLAY_NAME_MAPPINGS,
)
from .node_prompt_fusion import (
    NODE_CLASS_MAPPINGS as FUSION_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FUSION_DISPLAY_NAME_MAPPINGS,
)
from .node_align_reference import (
    NODE_CLASS_MAPPINGS as ALIGN_REFERENCE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ALIGN_REFERENCE_DISPLAY_NAME_MAPPINGS,
)
from .node_geometry_guard import (
    NODE_CLASS_MAPPINGS as GUARD_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GUARD_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **BUCKET_CLASS_MAPPINGS,
    **FUSION_CLASS_MAPPINGS,
    **GUARD_CLASS_MAPPINGS,
    **ALIGN_REFERENCE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **BUCKET_DISPLAY_NAME_MAPPINGS,
    **FUSION_DISPLAY_NAME_MAPPINGS,
    **GUARD_DISPLAY_NAME_MAPPINGS,
    **ALIGN_REFERENCE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
